import type { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://www.mudanzasmarino.com.ar";

  const blogSlugs = [
    "cuanto-cuesta-mudanza-buenos-aires",
    "como-organizar-mudanza-paso-a-paso",
    "mudanzas-edificios-buenos-aires",
    "checklist-mudanza",
    "como-embalar-muebles-mudanza",
    "que-incluye-una-mudanza",
    "mudanzas-por-soga",
    "guardamuebles-buenos-aires",
    "empresa-mudanzas-confiable-buenos-aires",
    "mudanzas-departamentos-buenos-aires",
    "mudanzas-con-y-sin-ascensor",
    "fletes-buenos-aires",
    "mudanzas-oficinas-buenos-aires",
    "mudanzas-larga-distancia-argentina",
    "mudanzas-palermo",
    "mudanzas-belgrano",
    "mudanzas-caballito",
    "mudanzas-recoleta",
    "mudanzas-flores",
    "mudanzas-almagro",
    "mudanzas-villa-urquiza",
    "mudanzas-san-telmo",
    "mudanzas-boedo",
    "mudanzas-villa-crespo",
    "mudanzas-nunez",
    "mudanzas-colegiales",
    "mudanzas-villa-devoto",
    "mudanzas-liniers",
    "mudanzas-mataderos",
    "mudanzas-vicente-lopez",
    "mudanzas-san-isidro",
    "mudanzas-tigre",
    "mudanzas-moron",
    "mudanzas-lanus",
    "mudanzas-quilmes",
    "mudanzas-avellaneda",
    "mudanzas-la-matanza",
    "mudanzas-con-mascotas",
    "mudanzas-en-invierno",
    "mudanzas-express-buenos-aires",
    "como-armar-cajas-mudanza",
    "mudanzas-chacarita",
    "mudanzas-saavedra",
    "mudanzas-parque-patricios",
    "mudanzas-montserrat",
    "mudanzas-hurlingham",
    "mudanzas-pilar",
    "mudanzas-san-fernando",
    "mudanzas-lomas-de-zamora",
    "mudanzas-fin-de-mes",
    "mudanzas-villa-del-parque",
    "mudanzas-parque-chacabuco",
    "mudanzas-paternal",
    "mudanzas-villa-pueyrredon",
    "mudanzas-agronomia",
    "mudanzas-villa-lugano",
    "mudanzas-balvanera",
    "mudanzas-floresta",
    "mudanzas-villa-santa-rita",
    "mudanzas-monte-castro",
    "mudanzas-villa-luro",
    "mudanzas-villa-general-mitre",
    "mudanzas-barracas",
    "mudanzas-constitucion",
    "mudanzas-nueva-pompeya",
    "mudanzas-villa-soldati",
    "mudanzas-villa-riachuelo",
    "mudanzas-boca",
    "mudanzas-merlo",
    "mudanzas-moreno",
    "mudanzas-san-martin",
    "mudanzas-tres-de-febrero",
    "mudanzas-berazategui",
    "mudanzas-jose-c-paz",
    "mudanzas-malvinas-argentinas",
    "mudanzas-esteban-echeverria",
    "mudanzas-florencio-varela",
    "mudanzas-ezeiza",
    "mudanzas-marcos-paz",
    "mudanzas-general-rodriguez",
    "mudanzas-retiro",
    "mudanzas-villa-ortuzar",
    "mudanzas-versalles",
    "mudanzas-villa-real",
    "mudanzas-lujan",
    "mudanzas-zarate",
    "como-calcular-volumen-mudanza",
    "como-preparar-electrodomesticos-mudanza",
    "mudanzas-con-ninos",
    "mudanzas-de-piano-buenos-aires",
    "que-no-transportan-las-empresas-de-mudanzas",
    "mudanzas-tortuguitas",
    "primer-departamento-buenos-aires",
    "mudanzas-en-verano",
    "como-entregar-departamento-alquilado",
    "como-ahorrar-en-tu-mudanza",
  ];

  return [
    { url: baseUrl, lastModified: new Date(), changeFrequency: "weekly", priority: 1 },
    { url: `${baseUrl}/blog`, lastModified: new Date(), changeFrequency: "weekly", priority: 0.9 },
    { url: `${baseUrl}/galeria`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.8 },
    { url: `${baseUrl}/mudanzas-residenciales`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${baseUrl}/mudanzas-oficinas`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${baseUrl}/guardamuebles`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    { url: `${baseUrl}/mudanzas-interior`, lastModified: new Date(), changeFrequency: "monthly", priority: 0.9 },
    ...blogSlugs.map((slug) => ({
      url: `${baseUrl}/blog/${slug}`,
      lastModified: new Date(),
      changeFrequency: "monthly" as const,
      priority: 0.8,
    })),
  ];
}
